#!/bin/bash

readonly state_ok=0
readonly state_warning=1
readonly state_critical=2
readonly state_unknown=3

#
# Print arguments joined by delimiter
#
# Arguments:
# - delim: Delimiter; may have multiple characters
# - args...: Values
#
# Source: https://stackoverflow.com/a/17841619
#
join_args() {
  local delim="$1"; shift
  echo -n "$1"; shift
  printf "%s" "${@/#/$delim}"
}

#
# Merge exit status
#
# Warning wins over OK, critical wins over warning
#
# Arguments:
# - Current value
# - Desired value
#
merge_status() {
  local cur="$1" update="$2"

  if (( cur < update )); then
    echo $update
  else
    echo $cur
  fi
}

run_oc() {
  local cfgfile="$1"; shift

  /usr/bin/oc --config="$cfgfile" -o json "$@"
}

finish() {
  local exit_status="$1"; shift
  local output=( "$@" )
  local combined

  case "$exit_status" in
    $state_ok)
      combined=OK
      ;;
    $state_warning)
      combined=WARNING
      ;;
    $state_critical)
      combined=CRITICAL
      ;;
    *)
      combined=UNKNOWN
      exit_status=$state_unknown
      ;;
  esac

  if [[ -v output && "${#output[@]}" -gt 0 ]]; then
    combined="$combined $(join_args ', ' "${output[@]}")"
  fi

  echo "$combined"
  exit $exit_status
}

# vim: set sw=2 sts=2 et :
